import { faker } from '@faker-js/faker'
import { PilotGender } from '../data/pilotPortraits'

export const MILITARY_CALLSIGNS = [
  'Viper',
  'Raven',
  'Ghost',
  'Reaper',
  'Maverick',
  'Bandit',
  'Hammer',
  'Falcon',
  'Saber',
  'Nomad',
  'Warden',
  'Sentinel',
  'Bulldog',
  'Lancer',
  'Outrider',
  'Cyclone',
  'Striker',
  'Titan',
  'Warlock',
  'Phoenix',
  'Kodiak',
  'Valkyrie',
  'Predator',
  'Tempest',
  'Raptor',
  'Coldfire',
  'Firebrand',
  'Gunsmoke',
  'Longshot',
  'Backblast',
  'Hardline',
  'Overwatch',
  'Nightfall',
  'Deadeye',
  'Crosswind',
  'Afterburn',
  'Shrapnel',
  'Wolfpack',
  'Broadside',
  'Highball',
  'Ironclad',
  'Dragoon',
  'Skylance',
  'Blackout',
  'Hotspur',
  'Ricochet',
  'Redline',
  'Stormfront',
  'Dustoff',
  'Sidewinder',
  'Thunderhead',
  'Warpath',
  'Skybolt',
  'Bluejay',
  'Jackknife',
  'Havoc',
  'Mongoose',
  'Foxhound',
  'Anvil',
  'Bulwark',
  'Breakaway',
  'Topspin',
  'Quickdraw',
  'Barrage',
  'Lockjaw',
  'Roadblock',
  'Shatter',
  'Ramjet',
  'Longbow',
  'Trident',
  'Riptide',
  'Greywolf',
  'Steeljaw',
  'Blaze',
  'Monsoon',
  'Talon',
  'Harpoon',
  'Ridgeback',
  'Wolfbane',
  'Nailgun',
  'Skyhammer',
  'Flint',
  'Cinder',
  'Comet',
  'Wraith',
  'Guardian',
  'Oracle',
  'Goliath',
  'Prowler',
  'Rampart',
  'Switchblade',
  'Grizzly',
  'Howler',
  'Nightjar',
  'Mako',
  'Stingray',
  'Riptalon',
  'Watchtower',
  'Ironhawk',
  'Skyreaper'
] as const

export const getRandomFirstName = (gender: PilotGender = PilotGender.Male): string =>
  faker.person.firstName(gender === PilotGender.Male ? 'male' : 'female')

export const getRandomLastName = (gender: PilotGender = PilotGender.Male): string =>
  faker.person.lastName(gender === PilotGender.Male ? 'male' : 'female')

export const getRandomCallsign = (): string => faker.helpers.arrayElement(MILITARY_CALLSIGNS)
